
# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
#formats: all
formats:
  #- epub
  - pdf
  - htmlzip

# Set the version of Python and other tools
build:
  os: ubuntu-22.04
  tools:
    #python: "3.11"
    python: "3" # last stable CPython version

python:
  install:
    - requirements: docs/requirements.txt
