
dist: xenial

branches:
  only:
  - master
  # Release branches
  - /^[0-9]+\.[0-9]+\.[0-9]+$/

os:
  - linux

compiler:
  - gcc
  - clang

#language:
#  - cpp
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

script:
- "./tests.py"
