
dist: xenial

branches:
  only:
  - master
  # Release branches
  - /^[0-9]+\.[0-9]+\.[0-9]+$/

os:
  - linux

language: python

matrix:
  include:
  - name: Python 2.7 on Linux
    python: 2.7
  - name: Python 3.5 on Linux
    python: 3.5
  - name: Python 3.6 on Linux
    python: 3.6
  - name: Python 3.7 on Linux
    python: 3.7
  - name: PyPy (with python 3.5) on Linux
    # https://docs.travis-ci.com/user/languages/python/#pypy-support
    # https://travis-ci.community/t/confusing-pypy-versions/2505
    # https://travis-ci.community/t/pypy-2-7-on-xenial/889
    python: pypy3.5
  - name: Python 2.7 on macOS
    os: osx
    language: shell
    env: PYENV_VERSION=2.7.12
  - name: Python 3.5 on macOS
    os: osx
    language: shell
    env: PYENV_VERSION=3.5.5
  - name: Python 3.6 on macOS
    os: osx
    language: shell
    env: PYENV_VERSION=3.6.5
  - name: Python 3.7 on macOS
    os: osx
    osx_image: xcode11 
    language: shell
    env: PYENV_VERSION=3.7.2
  - name: Python 3.7 on Windows
    # https://docs.travis-ci.com/user/reference/windows/
    # https://github.com/cclauss/Travis-CI-Python-on-three-OSes
    os: windows
    language: shell
    before_install:
      # by default choco installs last version of python
      - choco install python --version 3.7.2
      # I'm not sure that it's necessary
      - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      #set -ex
      #pip3 install --upgrade pip
      #eval "$(pyenv init -)"
      export PATH="$(pyenv root)/shims:${PATH}"
      #export PATH="$HOME/.pyenv/shims:${PATH}"
      #pyenv install --list
      pyenv install -s $PYENV_VERSION
      #pyenv versions
      # A manual check that the correct version of Python is running.
      python --version
      #set +ex
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      pip3 install --upgrade pip
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      python tests.py;
    else
      ./tests.py;
    fi;
