
dist: xenial

branches:
  only:
  - master
  # Release branches
  - /^[0-9]+\.[0-9]+\.[0-9]+$/

os:
  - linux

language: python

matrix:
  include:
  - name: Python 2.7 on Linux
    python: 2.7
  - name: Python 3.5 on Linux
    python: 3.5
  - name: Python 3.6 on Linux
    python: 3.6
  - name: Python 3.7 on Linux
    python: 3.7
  - name: Python 2.7 on macOS
    os: osx
    #osx_image: xcode7.3
    language: shell
    env: PYENV_VERSION=2.7.12
  - name: Python 3.5 on macOS
    os: osx
    language: shell
    env: PYENV_VERSION=3.5.5
  - name: Python 3.6 on macOS
    os: osx
    language: shell
    env: PYENV_VERSION=3.6.5
  - name: Python 3.7 on macOS
    os: osx
    osx_image: xcode10.2 
    language: shell
    env: PYENV_VERSION=3.7.2

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      set -ex
      brew update
      brew install openssl readline
      brew outdated pyenv || brew upgrade pyenv
      brew install pyenv-virtualenv
      pip3 install --upgrade pip
      #pyenv install --list
      pyenv install -s $PYENV_VERSION
      export PATH="$HOME/.pyenv/shims:${PATH}"
      pyenv-virtualenv venv
      source venv/bin/activate
      # A manual check that the correct version of Python is running.
      python --version
      set +ex
    fi

script:
- "./tests.py"
