
dist: xenial

branches:
  only:
  - master
  # Release branches
  - /^[0-9]+\.[0-9]+\.[0-9]+$/

os:
  - linux

#compiler:
#  - gcc
#  - clang

language: python
#python:
#  - "2.7"
#  - "3.5"
#  - "3.6"

matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - name: Python 2.7.12 on macOS
    os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12

script:
- "./tests.py"
