
dist: xenial

branches:
  only:
  - master
  # Release branches
  - /^[0-9]+\.[0-9]+\.[0-9]+$/

os:
  - linux

language: python

matrix:
  include:
  - name: Python 2.7 on Linux
    python: 2.7
  - name: Python 3.5 on Linux
    python: 3.5
  - name: Python 3.6 on Linux
    python: 3.6
  - name: Python 3.7 on Linux
    python: 3.7
  - name: Python 2.7.12 on macOS
    os: osx
    osx_image: xcode7.3
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - name: Python 3.5.5 on macOS
    os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.5
  - name: Python 3.6.5 on macOS
    os: osx
    language: objective-c
    env: PYENV_VERSION=3.6.5
  - name: Python 3.7.2 running on macOS 10.14.3
    os: osx
    osx_image: xcode10.2 
    language: shell

script:
- "./tests.py"
