name: CI

on:
  push:
    branches:
      - master
  #pull_request:
  #  branches:
  #    - master

jobs:
  ubuntu-python-3_5:

    #runs-on: ubuntu-latest
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: check python version
      run: python --version
    - name: install deps
      run: |
        sudo apt-get install clang gcc build-essential bison nasm yasm
                             gdc ldc libboost-all-dev lua5.1 libdbus-glib-1-dev