name: CI

on:
  push:
    branches:
      - master
  #pull_request:
  #  branches:
  #    - master

jobs:
  #ubuntu-python-3_5:
  tests:

    runs-on: ubuntu-18.04
    #runs-on: ubuntu-16.04

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        #os: [ubuntu-16.04, ubuntu-18.04]
        #python-version: [3.5, 3.6, 3.7, 3.8, 3.9, pypy3]
        python-version: [3.5, 3.6]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check python version
      run: python --version
    - name: Install apt packages
      run: |
        sudo apt-get install clang gcc build-essential bison nasm yasm
        sudo apt-get install gdc ldc libboost-all-dev lua5.1 libdbus-glib-1-dev
        sudo apt-get install gfortran libgtk-3-dev libsdl2-dev
    - name: Install pip modules
      run: |
        python -m pip install --upgrade pip
        #python -m pip install pyyaml
        #python -m pip install msgpack
        #python -m pip install pytest
        #python -m pip install pytest-cov
        #python -m pip install pytest-mock
        #python -m pip install coveralls
        pip install -r dev-requirements.txt
    - name: Run tests
      run: |
        python -m pytest --cov zm tests -v -k "not zipapp" --maxfail=2