name: CI

on:
  push:
    branches:
      - $default-branch
  #pull_request:
  #  branches: [ $default-branch ]

jobs:
  linux-python-3.5:

    #runs-on: ubuntu-latest
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: check python version
      run: python --version
    - name: install deps
      run: |
        sudo apt-get install build-essential bison nasm yasm