name: CI

on:
  push:
    branches:
      - master
  #pull_request:
  #  branches:
  #    - master

jobs:
  ubuntu-python-3_5:

    #runs-on: ubuntu-latest
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: check python version
      run: python --version
    - name: install apt packages
      run: |
        sudo apt-get install clang gcc build-essential bison nasm yasm
        sudo apt-get install gdc ldc libboost-all-dev lua5.1 libdbus-glib-1-dev
        sudo apt-get install gfortran libgtk-3-dev libsdl2-dev
    - name: install pip modules
      run: |
        sudo python -m pip install pyyaml
        sudo python -m pip install msgpack
        sudo python -m pip install pytest
        sudo python -m pip install pytest-cov
        sudo python -m pip install pytest-mock
        sudo python -m pip install coveralls
    - name: run tests
      run: |
        python -m pytest --cov zm tests -v -k "not zipapp" --maxfail=2